# Generated by Django 6.1.1 on 2026-09-22 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="manufacturer",
            options={"ordering": ("name",)},
        ),
    ]
