# Generated by Django 6.1.1 on 2026-09-22 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0003_alter_car_options_alter_driver_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="car",
            options={"ordering": ("id",)},
        ),
    ]
